// <auto-generated />
using System;
using Domain.Entities;
using Domain.Entities.toims;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(EGISManagementDbContext))]
    partial class EGISManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity<BillingTransaction>()
                .HasMany(x => x.Details)
                .WithOne(x => x.BillingTransaction)
                .HasForeignKey(x => x.BillingTransactionId)
                .OnDelete(DeleteBehavior.Cascade);

            modelBuilder.Entity("Domain.Entities.BatchReceipt", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("ReceiptId")
                    .IsRequired()
                    .HasColumnType("int");

                b.Property<DateOnly>("BatchDate")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.ToTable("BatchReceipt");
            });

            modelBuilder.Entity("Domain.Entities.Barangay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baranggay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaranggayCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Barangay");
                });

            modelBuilder.Entity("Domain.Entities.CollectionCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CollectionCode");
                });

            modelBuilder.Entity("Domain.Entities.CollectionSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Actual")
                        .HasColumnType("float");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<double>("BeginningBalance")
                        .HasColumnType("float");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CollectionSummary");
                });

            modelBuilder.Entity("Domain.Entities.CollectionSummaryDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                   
                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("SetDate")
                        .HasColumnType("date");

                    b.Property<double>("PerDayAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CollectionSummaryDetails");
                });

            modelBuilder.Entity("Domain.Entities.EstimatedRevenue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SetupYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EstimatedRevenue");
                });

            modelBuilder.Entity("Domain.Entities.ManagingTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ManagingTemplate");
                });

            modelBuilder.Entity("Domain.Entities.MasterTableCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("Createdat")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MasterTableCode");
                });

            modelBuilder.Entity("Domain.Entities.MasterTableSubCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Subcode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MasterTableSubCode");
                });

            modelBuilder.Entity("Domain.Entities.OfficialReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ReceiptNumber")
                        .HasColumnType("int");

                    b.Property<int>("SubCode")
                        .HasColumnType("int");

                    b.Property<string>("Char")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateIssue")
                        .HasColumnType("Date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OfficialReceipt");
                });

            modelBuilder.Entity("Domain.Entities.OfficialReceiptDetail", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("ReceiptNumber")
                    .HasColumnType("int");

                b.Property<string>("Code")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<double>("Amount")
                    .HasColumnType("double");

                b.HasKey("Id");

                b.ToTable("OfficialReceiptDetail");
            });

            modelBuilder.Entity("Domain.Entities.RevenueCodeChild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RevenueCodeChild");
                });

            modelBuilder.Entity("Domain.Entities.RevenueCodeForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Forms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RevenueCodeForm");
                });

            modelBuilder.Entity("Domain.Entities.RevenueCodeParent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeqNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RevenueCodeParent");
                });

            modelBuilder.Entity("Domain.Entities.Teller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teller");
                });

            modelBuilder.Entity("Domain.Entities.bpltas.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Bank");
                });

            modelBuilder.Entity("Domain.Entities.bpltas.Billing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessPermitId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<double>("NetDue")
                        .HasColumnType("float");

                    b.Property<double>("Penalty")
                        .HasColumnType("float");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TaxDue")
                        .HasColumnType("float");

                    b.Property<double>("TotalDue")
                        .HasColumnType("float");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Billings");
                });

            modelBuilder.Entity("Domain.Entities.toims.FormIssuance", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("BookNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Quantity")
                    .HasColumnType("int");

                b.Property<int>("StartReceipt")
                    .HasColumnType("int");

                b.Property<int>("EndReceipt")
                    .HasColumnType("int");

                b.Property<string>("Char")
                    .IsRequired()
                    .HasColumnType("nvarchar(10)");

                b.Property<int>("TellerCode")
                    .HasColumnType("int");

                b.Property<DateOnly>("FinalDate")
                    .HasColumnType("date");

                b.Property<DateTime>("DateAssigned")
                    .HasColumnType("date");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.ToTable("FormIssuance");
            });

            modelBuilder.Entity("Domain.Entities.toims.CashTicket", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("ControlNumber")
                    .IsRequired()
                    .HasColumnType("int");

                b.Property<int>("Quantity")
                    .HasColumnType("int");

                b.Property<double>("Amount")
                    .HasColumnType("float");

                b.Property<string>("TellerName")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("TellerCode")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.ToTable("CashTicket");
            });

            modelBuilder.Entity("Domain.Entities.toims.CheckReceivedDay", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("ReceiptNumber")
                    .HasColumnType("int");
                b.Property<int>("BankNumber")
                    .HasColumnType("int");
                b.Property<string>("BankName")
                    .HasColumnType("nvarchar(max)");
                b.Property<int>("CheckNumber")
                    .HasColumnType("int");
                b.Property<double>("CheckAmount")
                    .HasColumnType("float");
                b.Property<DateOnly>("CheckDate")
                    .HasColumnType("date");
                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.ToTable("CheckReceivedDay");
            });
            //RPTAS
            modelBuilder.Entity("Domain.Entities.rptas.Users", b =>
            {
                b.Property<int>("UserId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                b.Property<string>("UserName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Phone")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("UserId");
                b.ToTable("Users");
            });

            modelBuilder.Entity("Domain.Entities.rptas.Baranggays", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("ZoneNo")
                    .HasColumnType("int");

                b.Property<string>("City")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Province")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");
                b.ToTable("Baranggays");
            });

            modelBuilder.Entity("Domain.Entities.rptas.Properties", b =>
            {
                b.Property<int>("PropertyId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyId"));

                b.Property<int>("TaxDeclarationNo")
                    .HasColumnType("int");

                b.Property<int>("OwnerId")
                    .HasColumnType("int");

                b.Property<int>("TitleNo")
                    .HasColumnType("int");

                b.Property<string>("Classification")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Location")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("LandArea")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("PropertyStatus")
                    .HasColumnType("bit");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("PropertyId");
                b.HasIndex("OwnerId");
                b.ToTable("Properties");
            });

            modelBuilder.Entity("Domain.Entities.rptas.Assessments", b =>
            {
                b.Property<int>("AssessmentId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentId"));

                b.Property<int>("PropertyId")
                    .HasColumnType("int");

                b.Property<double>("AssessedValue")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
    
                b.Property<double>("MarketValue")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("AssessmentLevel")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateOnly>("AssessmentDate")
                    .HasColumnType("date");

                b.Property<DateOnly>("ValidUntil")
                    .HasColumnType("date");

                b.Property<int>("AssessedBy")
                    .HasColumnType("int");

                b.HasKey("AssessmentId");
                b.HasIndex("PropertyId");
                b.HasIndex("AssessedBy");
                b.ToTable("Assessments");
            });

            modelBuilder.Entity("Domain.Entities.rptas.AuditLogs", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.Property<string>("Action")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("EntityAffected")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("MyProperty")
                    .HasColumnType("datetime2");

                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("AuditLogs");
            });

            modelBuilder.Entity("Domain.Entities.rptas.TaxComputations", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("AssessmentId")
                    .HasColumnType("int");

                b.Property<double>("TaxYear")
                    .HasColumnType("float");

                b.Property<double>("BasicTax")
                    .HasColumnType("float");

                b.Property<double>("SefTax")
                    .HasColumnType("float");

                b.Property<double>("IdleLandTax")
                    .HasColumnType("float");

                b.Property<double>("TotalDue")
                    .HasColumnType("float");

                b.Property<double>("Discount")
                    .HasColumnType("float");

                b.Property<double>("Penalty")
                    .HasColumnType("float");

                b.Property<double>("FinalAmount")
                    .HasColumnType("float");

                b.Property<string>("Status")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("TaxComputationId");
                b.HasIndex("AssessmentId");
                b.ToTable("TaxComputations");
            });

            modelBuilder.Entity("Domain.Entities.rptas.Payments", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("TaxId")
                    .HasColumnType("int");

                b.Property<int>("PayerId")
                    .HasColumnType("int");

                b.Property<DateOnly>("PaymentDate")
                    .HasColumnType("date");

                b.Property<double>("AmountPaid")
                    .HasColumnType("float");

                b.Property<string>("PaymentMethod")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("ReceiptNo")
                    .HasColumnType("int");

                b.Property<int>("VerifiedBy")
                    .HasColumnType("int");

                b.HasKey("Id");
                b.HasIndex("TaxId");
                b.HasIndex("PayerId");
                b.HasIndex("VerifiedBy");
                b.ToTable("Payments");
            });

            modelBuilder.Entity("Domain.Entities.rptas.Reassessments", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("PropertyId")
                    .HasColumnType("int");

                b.Property<int>("RequestedBy")
                    .HasColumnType("int");

                b.Property<string>("Reason")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateOnly>("RequestedDate")
                    .HasColumnType("date");

                b.Property<DateOnly>("DateReviewed")
                    .HasColumnType("date");

                b.HasKey("Id");
                b.HasIndex("PropertyId");
                b.HasIndex("RequestedBy");
                b.ToTable("Reassessments");
            });

            modelBuilder.Entity("Domain.Entities.rptas.Delinquencies", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("TaxId")
                    .HasColumnType("int");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ActionTaken")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateOnly>("DateFlagged")
                    .HasColumnType("date");

                b.HasKey("Id");
                b.HasIndex("TaxId");
                b.ToTable("Delinquencies");
            });

            // Foreign key relationships
            modelBuilder.Entity("Domain.Entities.rptas.Properties", b =>
            {
                b.HasOne("Domain.Entities.rptas.Users", null)
                    .WithMany()
                    .HasForeignKey("OwnerId")
                    .OnDelete(DeleteBehavior.Cascade);
            });
            modelBuilder.Entity("Domain.Entities.rptas.Assessments", b =>
            {
                b.HasOne("Domain.Entities.rptas.Properties", null)
                    .WithMany()
                    .HasForeignKey("PropertyId")
                    .OnDelete(DeleteBehavior.Cascade);
                b.HasOne("Domain.Entities.rptas.Users", null)
                    .WithMany()
                    .HasForeignKey("AssessedBy")
                    .OnDelete(DeleteBehavior.Restrict);
            });
            modelBuilder.Entity("Domain.Entities.rptas.AuditLogs", b =>
            {
                b.HasOne("Domain.Entities.rptas.Users", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade);
            });
            modelBuilder.Entity("Domain.Entities.rptas.TaxComputations", b =>
            {
                b.HasOne("Domain.Entities.rptas.Assessments", null)
                    .WithMany()
                    .HasForeignKey("AssessmentId")
                    .OnDelete(DeleteBehavior.Cascade);
            });
            modelBuilder.Entity("Domain.Entities.rptas.Payments", b =>
            {
                b.HasOne("Domain.Entities.rptas.Properties", null)
                    .WithMany()
                    .HasForeignKey("TaxId")
                    .OnDelete(DeleteBehavior.Cascade);
                b.HasOne("Domain.Entities.rptas.Users", null)
                    .WithMany()
                    .HasForeignKey("PayerId")
                    .OnDelete(DeleteBehavior.Restrict);
                b.HasOne("Domain.Entities.rptas.Users", null)
                    .WithMany()
                    .HasForeignKey("VerifiedBy")
                    .OnDelete(DeleteBehavior.Restrict);
            });
            modelBuilder.Entity("Domain.Entities.rptas.Reassessments", b =>
            {
                b.HasOne("Domain.Entities.rptas.Properties", null)
                    .WithMany()
                    .HasForeignKey("PropertyId")
                    .OnDelete(DeleteBehavior.Cascade);
                b.HasOne("Domain.Entities.rptas.Users", null)
                    .WithMany()
                    .HasForeignKey("RequestedBy")
                    .OnDelete(DeleteBehavior.Restrict);
            });
            modelBuilder.Entity("Domain.Entities.rptas.Delinquencies", b =>
            {
                b.HasOne("Domain.Entities.rptas.TaxComputations", null)
                    .WithMany()
                    .HasForeignKey("TaxId")
                    .OnDelete(DeleteBehavior.Cascade);
            });
        }
    }
}
 